# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2.xci
# IP: The module: 'bd_top_axi_iic_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_axi_iic_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_axi_iic_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2.xci
# IP: The module: 'bd_top_axi_iic_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_axi_iic_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_axi_iic_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
