# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mycpu_0_0/bd_top_mycpu_0_0.xci
# IP: The module: 'bd_top_mycpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mycpu_0_0/bd_top_mycpu_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_mycpu_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mycpu_0_0/bd_top_mycpu_0_0.xci
# IP: The module: 'bd_top_mycpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/div_gen_0/div_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mycpu_0_0/bd_top_mycpu_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_mycpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
