# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Xilinx_Project/soc_like_0x7C00/vivado/soc_like_0x7C00.cache/wt [current_project]
set_property parent.project_path D:/Xilinx_Project/soc_like_0x7C00/vivado/soc_like_0x7C00.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Xilinx_Project/soc_like_0x7C00/ip [current_project]
update_ip_catalog
set_property ip_output_repo d:/Xilinx_Project/soc_like_0x7C00/vivado/soc_like_0x7C00.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/Xilinx_Project/soc_like_0x7C00/coe/eth_ping.coe
read_verilog -library xil_defaultlib D:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/hdl/bd_top_wrapper.v
add_files D:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/bd_top.bd
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_0_0/bd_top_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_0_0/bd_top_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_0_0/bd_top_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_1_0/bd_top_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_1_0/bd_top_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_1_0/bd_top_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_2_0/bd_top_clk_wiz_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_2_0/bd_top_clk_wiz_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_2_0/bd_top_clk_wiz_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_3_0/bd_top_clk_wiz_3_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_3_0/bd_top_clk_wiz_3_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_3_0/bd_top_clk_wiz_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_proc_sys_reset_0_0/bd_top_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_proc_sys_reset_0_0/bd_top_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_proc_sys_reset_0_0/bd_top_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mycpu_0_0/bd_top_mycpu_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xbar_0/bd_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_crossbar_0_0/bd_top_axi_crossbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_bram_ctrl_0_0/bd_top_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_blk_mem_gen_0_0/bd_top_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_gpu_top_0_1/bd_top_gpu_top_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_uart16550_0_0/bd_top_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_uart16550_0_0/bd_top_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_uart16550_0_0/bd_top_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_ethernetlite_0_0/bd_top_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_ethernetlite_0_0/bd_top_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_ethernetlite_0_0/bd_top_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_ethernetlite_0_0/bd_top_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_intc_0_0/bd_top_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_intc_0_0/bd_top_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_intc_0_0/bd_top_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mig_7series_0_0/bd_top_mig_7series_0_0/user_design/constraints/bd_top_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mig_7series_0_0/bd_top_mig_7series_0_0/user_design/constraints/bd_top_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_2/bd_top_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_2/bd_top_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_2/bd_top_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_5/bd_top_auto_pc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_0/bd_top_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_0/bd_top_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_0/bd_top_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_0/bd_top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_1/bd_top_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_2/bd_top_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_3/bd_top_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_4/bd_top_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_1/bd_top_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_1/bd_top_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_1/bd_top_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/bd_top_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilinx_Project/soc_like_0x7C00/xdc/soc_like_0x7C00.xdc
set_property used_in_implementation false [get_files D:/Xilinx_Project/soc_like_0x7C00/xdc/soc_like_0x7C00.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bd_top_wrapper -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bd_top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bd_top_wrapper_utilization_synth.rpt -pb bd_top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
