# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Xilinx_Project/soc_like_0x7C00/xdc/soc_like_0x7C00.xdc

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_ram || ORIG_REF_NAME==gpu_ram} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_axi_to_bram/gpu_axi_to_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_axi_to_bram || ORIG_REF_NAME==gpu_axi_to_bram} -quiet] -quiet

# Block Designs: D:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/bd_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top || ORIG_REF_NAME==bd_top} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_0_0/bd_top_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_clk_wiz_0_0 || ORIG_REF_NAME==bd_top_clk_wiz_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_1_0/bd_top_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_clk_wiz_1_0 || ORIG_REF_NAME==bd_top_clk_wiz_1_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_2_0/bd_top_clk_wiz_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_clk_wiz_2_0 || ORIG_REF_NAME==bd_top_clk_wiz_2_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_clk_wiz_3_0/bd_top_clk_wiz_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_clk_wiz_3_0 || ORIG_REF_NAME==bd_top_clk_wiz_3_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_proc_sys_reset_0_0/bd_top_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_proc_sys_reset_0_0 || ORIG_REF_NAME==bd_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mycpu_0_0/bd_top_mycpu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_mycpu_0_0 || ORIG_REF_NAME==bd_top_mycpu_0_0} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/div_gen_0/div_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/cpu_zqy/xilinx_ip/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xbar_0/bd_top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xbar_0 || ORIG_REF_NAME==bd_top_xbar_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_interconnect_0_0/bd_top_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_axi_interconnect_0_0 || ORIG_REF_NAME==bd_top_axi_interconnect_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_crossbar_0_0/bd_top_axi_crossbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_axi_crossbar_0_0 || ORIG_REF_NAME==bd_top_axi_crossbar_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_bram_ctrl_0_0/bd_top_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==bd_top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_blk_mem_gen_0_0/bd_top_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_blk_mem_gen_0_0 || ORIG_REF_NAME==bd_top_blk_mem_gen_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_spi_flash_ctrl_0_0/bd_top_spi_flash_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_spi_flash_ctrl_0_0 || ORIG_REF_NAME==bd_top_spi_flash_ctrl_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xlconstant_0_0/bd_top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xlconstant_0_0 || ORIG_REF_NAME==bd_top_xlconstant_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_confreg_0_1/bd_top_confreg_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_confreg_0_1 || ORIG_REF_NAME==bd_top_confreg_0_1} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_gpu_top_0_1/bd_top_gpu_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_gpu_top_0_1 || ORIG_REF_NAME==bd_top_gpu_top_0_1} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_ram || ORIG_REF_NAME==gpu_ram} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_axi_to_bram/gpu_axi_to_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_axi_to_bram || ORIG_REF_NAME==gpu_axi_to_bram} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_uart16550_0_0/bd_top_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_axi_uart16550_0_0 || ORIG_REF_NAME==bd_top_axi_uart16550_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xlconstant_0_1/bd_top_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xlconstant_0_1 || ORIG_REF_NAME==bd_top_xlconstant_0_1} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xlconstant_1_0/bd_top_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xlconstant_1_0 || ORIG_REF_NAME==bd_top_xlconstant_1_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_ethernetlite_0_0/bd_top_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_axi_ethernetlite_0_0 || ORIG_REF_NAME==bd_top_axi_ethernetlite_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_intc_0_0/bd_top_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_axi_intc_0_0 || ORIG_REF_NAME==bd_top_axi_intc_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_mig_7series_0_0/bd_top_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_mig_7series_0_0 || ORIG_REF_NAME==bd_top_mig_7series_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_axi_iic_0_2/bd_top_axi_iic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_axi_iic_0_2 || ORIG_REF_NAME==bd_top_axi_iic_0_2} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_util_vector_logic_0_0/bd_top_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_util_vector_logic_0_0 || ORIG_REF_NAME==bd_top_util_vector_logic_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_reset_synchronizer_0_0/bd_top_reset_synchronizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_reset_synchronizer_0_0 || ORIG_REF_NAME==bd_top_reset_synchronizer_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xlconcat_0_0/bd_top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xlconcat_0_0 || ORIG_REF_NAME==bd_top_xlconcat_0_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xlconcat_0_1/bd_top_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xlconcat_0_1 || ORIG_REF_NAME==bd_top_xlconcat_0_1} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xlconstant_0_2/bd_top_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xlconstant_0_2 || ORIG_REF_NAME==bd_top_xlconstant_0_2} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_xlconstant_0_3/bd_top_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_xlconstant_0_3 || ORIG_REF_NAME==bd_top_xlconstant_0_3} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_2/bd_top_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_cc_2 || ORIG_REF_NAME==bd_top_auto_cc_2} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_5/bd_top_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_pc_5 || ORIG_REF_NAME==bd_top_auto_pc_5} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_0/bd_top_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_cc_0 || ORIG_REF_NAME==bd_top_auto_cc_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_0/bd_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_pc_0 || ORIG_REF_NAME==bd_top_auto_pc_0} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_1/bd_top_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_pc_1 || ORIG_REF_NAME==bd_top_auto_pc_1} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_2/bd_top_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_pc_2 || ORIG_REF_NAME==bd_top_auto_pc_2} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_3/bd_top_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_pc_3 || ORIG_REF_NAME==bd_top_auto_pc_3} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_pc_4/bd_top_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_pc_4 || ORIG_REF_NAME==bd_top_auto_pc_4} -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_auto_cc_1/bd_top_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_top_auto_cc_1 || ORIG_REF_NAME==bd_top_auto_cc_1} -quiet] -quiet

# XDC: d:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram_ooc.xdc

# XDC: d:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram_ooc.xdc

# XDC: D:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/bd_top_ooc.xdc
