# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_gpu_top_0_1/bd_top_gpu_top_0_1.xci
# IP: The module: 'bd_top_gpu_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_ram || ORIG_REF_NAME==gpu_ram} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_axi_to_bram/gpu_axi_to_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_axi_to_bram || ORIG_REF_NAME==gpu_axi_to_bram} -quiet] -quiet

# XDC: d:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram_ooc.xdc

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_gpu_top_0_1/bd_top_gpu_top_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_gpu_top_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_gpu_top_0_1/bd_top_gpu_top_0_1.xci
# IP: The module: 'bd_top_gpu_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_ram || ORIG_REF_NAME==gpu_ram} -quiet] -quiet

# IP: D:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_axi_to_bram/gpu_axi_to_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpu_axi_to_bram || ORIG_REF_NAME==gpu_axi_to_bram} -quiet] -quiet

# XDC: d:/Xilinx_Project/soc_like_0x7C00/src/gpu_wh/gpu_ram/gpu_ram_ooc.xdc

# XDC: d:/Xilinx_Project/soc_like_0x7C00/bd/bd_top/ip/bd_top_gpu_top_0_1/bd_top_gpu_top_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_top_gpu_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
